language: python

python:
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements/dev.txt
  - pip install tox-travis

script:
  - tox
  - coverage run --source icon_font_to_png -m py.test
  - coverage report -m

after_success:
  - coveralls